<a href="https://colab.research.google.com/github/PratikHazarika/AI-ML-Projects/blob/main/ML%20Algorithms/Ad%20Click%20Prediction/DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

import warnings
warnings.filterwarnings('ignore')

Mounted at /content/gdrive/


In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Ad Prediction/advertising.csv')

In [ ]:
df.drop(['Ad Topic Line', 'City', 'Country', 'Timestamp'], axis = 'columns', inplace=True)
df.rename({'Daily Time Spent on Site':'Time Spent', 'Area Income':'Income', 'Daily Internet Usage':'Internet Usage', 'Clicked on Ad':'Clicked', 'Male': 'Gender'}, axis='columns', inplace=True)

In [ ]:
df

Time Spent  Age    Income  Internet Usage  Gender  Clicked
0         68.95   35  61833.90          256.09       0        0
1         80.23   31  68441.85          193.77       1        0
2         69.47   26  59785.94          236.50       0        0
3         74.15   29  54806.18          245.89       1        0
4         68.37   35  73889.99          225.58       0        0
..          ...  ...       ...             ...     ...      ...
995       72.97   30  71384.57          208.58       1        1
996       51.30   45  67782.17          134.42       1        1
997       51.63   51  42415.72          120.37       1        1
998       55.55   19  41920.79          187.95       0        0
999       45.01   26  29875.80          178.35       0        1

[1000 rows x 6 columns]

# Splitting the dataset

In [ ]:
X = df[['Time Spent', 'Age', 'Income','Internet Usage', 'Gender']]
y = df['Clicked']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, shuffle=False)

# Convert dataframe to numpy array

In [ ]:
features_arr = X.to_numpy()
target_arr = y.to_numpy()

np.array(map(str, features_arr))

array(<map object at 0x7f5fbd469b10>, dtype=object)

In [ ]:
print(type(features_arr))
print(type(target_arr))

print(features_arr.shape)
print(target_arr.shape)

print(features_arr)

features_arr.dtype

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(1000, 5)
(1000,)
[[6.895000e+01 3.500000e+01 6.183390e+04 2.560900e+02 0.000000e+00]
 [8.023000e+01 3.100000e+01 6.844185e+04 1.937700e+02 1.000000e+00]
 [6.947000e+01 2.600000e+01 5.978594e+04 2.365000e+02 0.000000e+00]
 ...
 [5.163000e+01 5.100000e+01 4.241572e+04 1.203700e+02 1.000000e+00]
 [5.555000e+01 1.900000e+01 4.192079e+04 1.879500e+02 0.000000e+00]
 [4.501000e+01 2.600000e+01 2.987580e+04 1.783500e+02 0.000000e+00]]


dtype('float64')

# Training 

In [ ]:
decision_tree_model = DecisionTreeClassifier()
decision_tree_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target

clf = DecisionTreeClassifier(random_state=1234)
model = clf.fit(X, y)

# print(type(X))
# print(type(y))

# print(X.shape)
# print(y.shape)

# print(X)

fig = plt.figure(figsize=(25,20))
_ = tree.plot_tree(decision_tree_model, 
                   feature_names=features_arr,  
                   class_names=target_arr)


# Accuracy

In [ ]:
accuracy = decision_tree_model.score(X_test, y_test)
print(f'The accuracy of the model: {accuracy * 100}')

The accuracy of the model: 95.5


# Classification Matrix

In [ ]:
predictions = decision_tree_model.predict(X_test)

actual = y_test
predicted = predictions

matrix = confusion_matrix(actual, predicted, labels = [1,0])
print(f'Confusion matrix : \n {matrix} \n\n')

tp, fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)
print(f'True positive: {tp} \t True Negative: {tn}')
print(f'False positive: {fp} \t False Negative: {fn} \n\n')

matrix = classification_report(actual, predicted, labels=[1,0])
print('Classification report : \n',matrix)

Confusion matrix : 
 [[105   7]
 [  2  86]] 


True positive: 105 	 True Negative: 86
False positive: 2 	 False Negative: 7 


Classification report : 
               precision    recall  f1-score   support

           1       0.98      0.94      0.96       112
           0       0.92      0.98      0.95        88

    accuracy                           0.95       200
   macro avg       0.95      0.96      0.95       200
weighted avg       0.96      0.95      0.96       200

